### ISSUE TITLE
Can I use it for time series forecasting or anomaly detection?

### ISSUE THREAD

**Issue by 943fansi** [mqwfrog/MHCCL#1]

**Comment by mqwfrog** [comment]
Sorry, it is currently not possible to directly use it for forecasting or anomaly detection. In this work, we regard the entire time series as an instance, while not focusing on timestamp-level representations. Therefore, you can use MHCCL to obtain instance-level representations. But if you wanna change the downstream task , you'd better modify the encoding method and the loss function.

**Comment by 943fansi** [comment]
@mqwfrog. Thanks for your answer!
