### ISSUE TITLE
DataSet

### ISSUE THREAD

**Issue by zifei-yu** [mqwfrog/MHCCL#5]

**Comment by zifei-yu** [comment]
Hello, where is your dataset located？

**Comment by mqwfrog** [comment]
All the datasets are publicly accessible and can be found following the links and references provided in the paper (https://arxiv.org/abs/2212.01141). Once you have downloaded the datasets, you can utilize the data preprocessing file provided in this repository to process them in an efficient manner.

**Comment by zifei-yu** [comment]
The dataset has been found. Thank you very much for your help.

**Comment by zifei-yu** [comment]
> 所有数据集均可公开访问，并且可以通过论文中提供的链接和参考文献找到（https://arxiv.org/abs/2212.01141）。下载数据集后，您可以利用此存储库中提供的数据预处理文件来有效地处理它们。

您好，我将您的模型改为CPU版本且不使用分布式进行训练，我首先使用“main.py”程序跑出来一个“'experiment_HAR/checkpoint_0014.pth.tar'”的压缩文件，然后使用“classifier.py”程序将其进行加载然后进行下游任务，不知道做法是否正确，导致最后没有图片输出，恳请您指点一下。
下面的图片是我运行程序之后最后的结果。

![1688459804647](https://github.com/mqwfrog/MHCCL/assets/63730604/34b9516e-a3e4-4f20-89ab-6049764ee132)
