### ISSUE TITLE
Good Jobs！

### ISSUE THREAD

**Issue by luojike2333** [mqwfrog/MHCCL#6]
Good Jobs！
Hello, author.After reading your code, I have a question that the model designed specifically for multivariate time series? Does that mean  can't run on a univariate time series.

**Comment by mqwfrog** [comment]
Hi ~ This model also works with univariate time series, you can set in_channels to 1. As reported in the paper, Epilepsy is a dataset with 1 variable (i.e., univariate time series).

**Comment by blacksnail789521** [comment]
Hello, @mqwfrog 

I have a question regarding the Epilepsy dataset mentioned in your paper. In the paper, you indicate that the dataset is sourced from UCI and that it has only one feature. However, upon reviewing your code, I found only `data_preprocess_wisdm`, `data_preprocess_HAR`, `data_preprocess_SHAR`, and `data_preprocess_UEA` methods, but nothing specifically for Epilepsy. This suggests that the Epilepsy dataset might actually be from UEA, not UCI, which is my first point of confusion.

Secondly, while there is indeed an Epilepsy dataset at UEA, it contains four features, not just one as mentioned in your paper. Could you please clarify these discrepancies? Your assistance would be greatly appreciated, and I thank you again for your contribution.

Best regards,

**Comment by mqwfrog** [comment]
Hi~ The data_preprocess_epilepsy file has been updated. The source of Epilepsy dataset that I used is now unavailable, so the source file is also uploaded in the same folder. The source file is downloaded from https://github.com/emadeldeen24/TS-TCC. You can refer to project TSTCC to get more details.
