### ISSUE TITLE
Issues Encountered with Dataset Setup as Listed in the Paper

### ISSUE THREAD

**Issue by blacksnail789521** [mqwfrog/MHCCL#7]
Hi,

I am attempting to set up the 7 datasets as listed in your paper, and I've encountered several issues. I was able to work with some datasets from [UCI](https://archive.ics.uci.edu/ml/datasets.html) and [UEA](http://www.timeseriesclassification.com/dataset.php), but others presented challenges.

### PenDigits, EigenWorms, FingerMovements
- For these UEA datasets, there were no issues.

### HAR
- The HAR dataset was downloaded from the [UCI repository](https://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).
- After preprocessing, the HAR dataset matches the number of features and time length as expected.
  ![HAR Dataset Preprocessing](https://github.com/mqwfrog/MHCCL/assets/5949636/b417607a-6cc9-4288-a642-fa4db0ec7bd6)

### Epilepsy
- There seems to be a confusion whether the Epilepsy dataset belongs to UCI or UEA, as discussed in this [issue](https://github.com/mqwfrog/MHCCL/issues/6#issuecomment-1790666120).
- When using the Epilepsy dataset from UEA, there is a mismatch in the number of features and the time length expected as per the paper. An illustration of the issue is shown below:
  ![Epilepsy Dataset Issue](https://github.com/mqwfrog/MHCCL/assets/5949636/dbda521e-bee1-45f9-91b8-0ac86f316dfb)

### WISDM
- I encountered issues when trying to preprocess the dataset (downloaded from the [UCI repository](https://archive.ics.uci.edu/dataset/507/wisdm+smartphone+and+smartwatch+activity+and+biometrics+dataset)) with the provided code. The code references a specific file named `WISDM_ar_v1.1_raw.txt`, which was not available in the downloaded files.
- In an attempt to locate the correct version of the dataset, I searched Google and found a potential match on [Kaggle](https://www.kaggle.com/datasets/paulopinheiro/wireless-sensor-data).
- Despite finding this file and attempting to preprocess it, there remains a mismatch in the number of features and the time length compared to what is expected based on the information in the paper.
  ![WISDM Dataset Preprocessing Issue](https://github.com/mqwfrog/MHCCL/assets/5949636/ce3cb606-febb-4928-bd33-ff8fd0af8bf3)

### SHAR
- I am unable to locate the SHAR dataset. While I did find a [related dataset on Kaggle](https://www.kaggle.com/datasets/alirezacman/unimib-shar), it does not contain a `.mat` file, which seems to be required for the preprocessing code provided.

I would appreciate any assistance or guidance on accessing and preprocessing these datasets correctly.

Thank you.

**Comment by mqwfrog** [comment]
Hi~
1. The confusion about the Eplipesy dataset has been explained in another issue you have commented on.
2. The source file of WISDM dataset "WISDM_ar_v1.1_raw.txt" cannot be uploaded due to file size limitations. I will email the source file to you later.
3. For more details about SHAR dataset, please refer to the paper "UniMiB SHAR: a new dataset for human activity recognition using acceleration data from smartphones, D. Micucci and M. Mobilio and P. Napoletano".

**Comment by blacksnail789521** [comment]
Thank you for your assistance with the dataset issue I've encountered. May I kindly request that you also email me the source data for the SHAR dataset, which is compatible with your preprocessing code?

**Comment by mqwfrog** [comment]
My email was returned. Please check. [ Reason: Message's size exceed or recipient over quota. ]

**Comment by blacksnail789521** [comment]
I have sent you an email with the location where you can upload all the files. Thank you again for your help. :)

My email is: blacksnail789521@gmail.com, and I've sent the link to your email: mqw_sdu@mail.sdu.edu.cn

@mqwfrog I really appreciate your help, and thank you for your outstanding work.
